---
name: dzil build and test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "15 4 * * 0" # Every Sunday morning
  workflow_dispatch:

jobs:
  build-job:
    name: Build distribution
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.36
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        env:
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
        run: upgrade-perl-helpers && auto-build-and-test-dist
      - uses: actions/upload-artifact@v3
        with:
          name: build_dir
          path: build_dir
  coverage-job:
    name: Coverage
    needs: build-job
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.36
    steps:
      - uses: actions/checkout@v4 # codecov wants to be inside a Git repository
      - uses: actions/download-artifact@v3
        with:
          name: build_dir
          path: .
      - name: Install deps and test
        run: cpan-install-dist-deps --with-develop && test-dist
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
  http-one-one-regression-job:
    name: HTTP/1.1 Keepalive Regression Test - see GH \# 14
    needs: build-job
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.34
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build_dir
          path: .
      - name: Install deps including curl and test
        run: >
          cpan-install-dist-deps --with-develop
          && cpanm LWP::Protocol::Net::Curl
      - name: test
        run: test-dist
        env:
          PERL5OPT: -MLWP::Protocol::Net::Curl=http_version,2
  test-linux:
    name: "${{ matrix.perl-version }} on Linux"
    needs: build-job
    runs-on: ubuntu-latest
    container:
      image: "perldocker/perl-tester:${{ matrix.perl-version }}"
    strategy:
      matrix:
        perl-version:
          - "5.8"
          - "5.10"
          - "5.12"
          - "5.14"
          - "5.16"
          - "5.18"
          - "5.20"
          - "5.22"
          - "5.24"
          - "5.26"
          - "5.28"
          - "5.30"
          - "5.32"
          - "5.34"
          - "5.36"
    steps:
      - name: pin Test::Deep to 1.130 on Perl < 5.12
        if: ${{ matrix.perl-version == '5.8' || matrix.perl-version == '5.10' }}
        run: cpanm --notest Test::Deep@1.130
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: build_dir
          path: .
      - name: Install deps and test
        run: cpan-install-dist-deps && test-dist
  test-macos:
    name: ${{ matrix.perl-version }} on macos-latest
    needs: test-linux
    runs-on: macos-latest
    strategy:
      matrix:
        perl-version:
          - "5.8"
          - "5.10"
          - "5.12"
          - "5.14"
          - "5.16"
          - "5.18"
          - "5.20"
          - "5.22"
          - "5.24"
          - "5.26"
          - "5.28"
          - "5.30"
          - "5.32"
          - "5.34"
          - "5.36"
    steps:
      - name: Set Up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - name: pin Test::Deep to 1.130 on Perl < 5.12
        if: ${{ matrix.perl-version == '5.8' || matrix.perl-version == '5.10' }}
        run: cpm install --global Test::Deep@1.130
      - uses: actions/download-artifact@v3
        with:
          name: build_dir
          path: .
      - name: install deps using cpm
        uses: perl-actions/install-with-cpm@v1.3
        with:
          cpanfile: "cpanfile"
          args: "--with-suggests --with-test"
      - run: prove -lr t
  test-windows:
    name: ${{ matrix.perl-version }} on windows-latest
    needs: test-linux
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        perl-version:
          - "5.14"
          - "5.16"
          #- "5.18" https://github.com/libwww-perl/WWW-Mechanize/runs/822568352?check_suite_focus=true
          - "5.20"
          - "5.22"
          - "5.24"
          - "5.26"
          - "5.28"
          - "5.30"
          - "5.32"
    steps:
      - name: Set Up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
          distribution: strawberry # this option only used on Windows
      - name: pin Test::Deep to 1.130 on Perl < 5.12
        if: ${{ matrix.perl-version == '5.8' || matrix.perl-version == '5.10' }}
        run: cpm install --global Test::Deep@1.130
      - uses: actions/download-artifact@v3
        with:
          name: build_dir
          path: .
      - name: install deps using cpm
        uses: perl-actions/install-with-cpm@v1.3
        with:
          cpanfile: "cpanfile"
          args: "--with-suggests --with-test --with-develop"
      - run: cpanm --test-only -v .
